
name = "cybertrack"
compatibility_date = "2024-02-08"
pages_build_output_dir = "dist"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "cybertrack-db"
database_id = "3048df8f-b102-450b-9f35-351a6dac9587"
